- name: Ping webservers playbook
  hosts: webservers
  tasks:
    - name: Ping my webserver
      ansible.builtin.ping:

- name: Upgrade packages in apt
  hosts: webservers
  tasks:
    - name: Upgrade packages in apt
      ansible.builtin.import_tasks: ../tasks/task_apt_upgrade_packages.yaml